version: 2

run:
  timeout: 5m
  go: "1.24"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - funlen
    - nestif
  disable:
    - revive
linters-settings:
  funlen:
    lines: 150
    statements: 60
  nestif:
    min-complexity: 4
  dupl:
    threshold: 100

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
