run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - funlen
    - nestif
  disable:
    - revive

linters-settings:
  funlen:
    lines: 150
    statements: 60
  nestif:
    min-complexity: 4
